// Code generated by "stringer -type=GPT4Mode"; DO NOT EDIT.

package chat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GPT4ModeTurbo-1]
}

const _GPT4Mode_name = "GPT4ModeTurbo"

var _GPT4Mode_index = [...]uint8{0, 13}

func (i GPT4Mode) String() string {
	i -= 1
	if i < 0 || i >= GPT4Mode(len(_GPT4Mode_index)-1) {
		return "GPT4Mode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _GPT4Mode_name[_GPT4Mode_index[i]:_GPT4Mode_index[i+1]]
}
